#- Is a configuration file for pytest, a testing framework for Python. It allows you to specify various settings and options for running tests.

[pytest]
addopts = --headed --browser chromium --html=reports/report.html --self-contained-html
testpaths = tests --slowmo=200